import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import { SidebarProvider } from "@/context/sidebar-context";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <SidebarProvider>
          <div className="flex flex-col h-screen">
            <Header />
            <div className="flex flex-1 pt-16">
              <Sidebar />
              <main className="flex-1 p-4 overflow-auto">{children}</main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
